variables:
  MAVEN_VERSION: 3.9.11-eclipse-temurin-21
  MAVEN_OPTS: -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  MAVEN_ARGS: >
              -s settings.xml
              -Pdefault
              -Dorg.slf4j.simpleLogger.defaultLogLevel=error
  GET_OFFLINE: "-o"
  TRIGGER_CACHE: "off"

image: maven:${MAVEN_VERSION}

stages:
  - building
  - testing


build:
  stage: building
  tags:
    - formation
  before_script:
    - cd java_sb
  script:
    - mvn test
  cache:
    key: deps
    policy: push
    paths:
      - .m2/repository
  # règles d'exécution du job
  # chaque règle VRAIE rend le job exécuté => OU logique
  rules:
    # si toutes les clauses (ici changes et when) sont vraies alors la règle est Vraie => ET logique
    - changes:
        - java_sb/pom.xml
      # s'exécute le job précédent en succès (vraie par défaut)
      # when: on_success
    - if: $TRIGGER_CACHE == "on"

test:
  stage: testing
  tags:
    - formation
  before_script:
    - cd java_sb
  script:
    - mvn test $GET_OFFLINE
    # - mvn test
  cache:
    key: deps
    policy: pull
    untracked: true