variables:
  MAVEN_VERSION: 3.9.11-eclipse-temurin-21
  MAVEN_OPTS: -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  MAVEN_ARGS: >
              -s settings.xml
              -Pdefault
              -Dorg.slf4j.simpleLogger.defaultLogLevel=error
  GET_OFFLINE: "-o"
  TRIGGER_CACHE: "off"

image: maven:${MAVEN_VERSION}

stages:
  - building
  - testing
  - qualifying


build:
  stage: building
  tags:
    - formation
  before_script:
    - cd java_sb
  script:
    # télécharger les dépendences du projet
    - mvn test
    # forcer toutes les dépendences (hors projet test ...)
    - mvn dependency:go-offline
    # idem pour les plugins
    - mvn dependency:resolve-plugins
  cache:
    key: deps
    policy: push
    paths:
      - .m2/repository
  rules:
    - changes:
        - java_sb/pom.xml
    - if: $TRIGGER_CACHE == "on"

# préfixer un job avec "." => désactive le job
.test:
  stage: testing
  tags:
    - formation
  before_script:
    - cd java_sb
  script:
    - mvn test $GET_OFFLINE
    - cat target/site/jacoco/index.html
  coverage: /Total</td><td class="bar">[0-9]{1,3} of [0-9]{1,3}</td><td class="ctr2">([0-9]{1,3})/
  artifacts:
    access: developer
    expire_in: "1 hour"
    paths:
      - java_sb/target/site/jacoco/jacoco.xml
    reports:
      junit: java_sb/target/surefire-reports/TEST-*.xml
      coverage_report:
        coverage_format: jacoco
        path: java_sb/target/site/jacoco/jacoco.xml
  cache:
    key: deps
    policy: pull
    untracked: true


sonar:
  stage: qualifying
  tags:
    - formation
  before_script:
    - cd java_sb
  script:
    # ">": convertit les sauts de lignes en espace
    # SONAR_TOKEN vient de settings > CICD > variables > add variables ...
    - >
      mvn sonar:sonar
      -Dsonar.projectKey=java_sb
      -Dsonar.java.binaries=target
      -Dsonar.host.url=http://gitlab.lan.fr:9000
      -Dsonar.login=$SONAR_TOKEN
  cache:
    key: deps
    policy: pull
    untracked: true
    
  