variables:
  MAVEN_VERSION: 3.9.11-eclipse-temurin-21
  MAVEN_OPTS: -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

image: maven:${MAVEN_VERSION}

## gestion de dépendances
# 1. déporter l'installation des dépendances dans un job inital
# 2. créer un cache dans gitlab à partir du dossier contenant les dépendances
# 2b. réutiliser le cache pour le job test et tous les jobs suivants utilisant maven
# 3. si le cache est valide (si les denpendances n'ont pas changé) => je n'exécute pas le job initial
# 3b: si le cache est supprimé en dehors du CI/CD => je me donne une procédure manuelle pour exécuter le job initial

stages:
  - building
  - testing


build:
  stage: building
  tags:
    - formation
  before_script:
    - cd java_sb
  script:
    - mvn compile
  cache:
    key: deps
    policy: push
    paths:
      - .m2/repository

test:
  stage: testing
  tags:
    - formation
  before_script:
    - cd java_sb
  script:
    - mvn test
  cache:
    key: deps
    # utilisation pure du cache mais on ne met pas à jour le cache
    policy: pull
    # untracked => nouveau fichier dans un dépôt git jamais commité
    # en gitlab => par défaut gitlab nettoie le dépôt après son installation (git clean) qui dégagent les fichier untracked
    # => le cache qui nécessairement untracked DEGAGE !!!
    # untracked true => permet de conserver le cache
    untracked: true