variables:
  MAVEN_VERSION: 3.9.11-eclipse-temurin-21
  MAVEN_OPTS: -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  MAVEN_ARGS: >
              -s settings.xml
              -Pdefault
              -Dorg.slf4j.simpleLogger.defaultLogLevel=error
  GET_OFFLINE: "-o"
  TRIGGER_CACHE: "off"

image: maven:${MAVEN_VERSION}

stages:
  - building
  - testing


build:
  stage: building
  tags:
    - formation
  before_script:
    - cd java_sb
  script:
    - mvn test
  cache:
    key: deps
    policy: push
    paths:
      - .m2/repository
  # règles d'exécution du job
  # chaque règle VRAIE rend le job exécuté => OU logique
  rules:
    # si toutes les clauses (ici changes et when) sont vraies alors la règle est Vraie => ET logique
    - changes:
        - java_sb/pom.xml
      # s'exécute le job précédent en succès (vraie par défaut)
      # when: on_success
    - if: $TRIGGER_CACHE == "on"

test:
  stage: testing
  tags:
    - formation
  before_script:
    - cd java_sb
  script:
    - mvn test $GET_OFFLINE
    # - mvn test
        # afficher le résultat de la couverture TOTALE dans la console du job
    - cat target/site/jacoco/index.html
  # capturer la ligne de console qui contient la couverture TOTALE
  coverage: /Total</td><td class="bar">[0-9]{1,3} of [0-9]{1,3}</td><td class="ctr2">([0-9]{1,3})/
  artifacts:
    access: developer
    expire_in: "1 hour"
    paths:
      - java_sb/target/site/jacoco/jacoco.xml
    reports:
      junit: java_sb/target/surefire-reports/TEST-*.xml
      coverage_report:
        coverage_format: jacoco
        path: java_sb/target/site/jacoco/jacoco.xml
  cache:
    key: deps
    policy: pull
    untracked: true