# "&" : référence qui désigne le contenu de la clé
.cache: &cache
  key: deps
  policy: pull
  untracked: true

.tag_required: &tag_required $CI_COMMIT_TAG =~ /v\d+\.\d+$/ 
.main_required: &main_required $CI_COMMIT_BRANCH == "main"
  
############## clés globales ##################################

variables:
  MAVEN_VERSION: 3.9.11-eclipse-temurin-21
  GECKODRIVER_VERSION: v0.36.0-linux64
  MAVEN_OPTS: -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  MAVEN_ARGS: >
              -s settings.xml
              -Pdefault
              -Dorg.slf4j.simpleLogger.defaultLogLevel=error
  GET_OFFLINE: "-o"
  TRIGGER_CACHE: "off"

image: maven:${MAVEN_VERSION}

before_script:
  - cd java_sb


############## stages ###########################################

stages:
  - building
  - testing
  - qualifying
  - staging
  - browsing

############## jobs #############################################

build:
  stage: building
  tags:
    - formation
  script:
    - mvn verify sonar:sonar || exit 0
    # - mvn package -Dmaven.test.skip=true
  cache:
    key: deps
    policy: push
    paths:
      - .m2/repository
  rules:
    - changes:
        - java_sb/pom.xml
    - if: $TRIGGER_CACHE == "on"

.test:
  stage: testing
  tags:
    - formation
  script:
    # on enlève la classe CucumberTest qui exécutent les tests d'interfaces
    - mvn test $GET_OFFLINE -Dtest=!CucumberTest
    - cat target/site/jacoco/index.html
  coverage: /Total</td><td class="bar">[0-9]{1,3} of [0-9]{1,3}</td><td class="ctr2">([0-9]{1,3})/
  artifacts:
    access: developer
    expire_in: "1 hour"
    paths:
      - java_sb/target/site/jacoco/jacoco.xml
    reports:
      junit: java_sb/target/surefire-reports/TEST-*.xml
      coverage_report:
        coverage_format: jacoco
        path: java_sb/target/site/jacoco/jacoco.xml
  # ALIAS YAML permet d'accrocher le contenu du &cache
  cache: *cache


.sonar:
  stage: qualifying
  tags:
    - formation
  script: 
    - >
      mvn sonar:sonar $GET_OFFLINE
      -Dsonar.projectKey=java_sb
      -Dsonar.java.binaries=target
      -Dsonar.host.url=http://gitlab.lan.fr:9000
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.coverage.jacoco.xmlReportPaths=java_sb/target/site/jacoco/jacoco.xml
      -Dsonar.qualitygate.wait=true
  cache: *cache

######## deploy #############################

.staging:
  stage: staging
  tags:
    - formation
  script:
    - mvn package -Dmaven.test.skip=true
    # utilisation du registre de paquet "générique" dans gitlab: Deploy > Package Registry
    - >
      curl
      -k --header "JOB-TOKEN: $CI_JOB_TOKEN"
      --upload-file target/java-sb.war
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/java_sb/staging-rc/java-sb.war"
  environment:
    name: staging
    url: https://dawan.fr
  rules:
    - if: *tag_required
    - if: *main_required
  cache: *cache


e2e:
  stage: browsing
  tags:
    - formation
  services:
    - name: selenium/standalone-firefox
      alias: selenium-server
  before_script:
    - >
      tar 
      -xzf geckodriver-${GECKODRIVER_VERSION}.tar.gz
      -C /usr/local/bin
    - chmod u+x /usr/local/bin/geckodriver
    - cd java_sb
  script:
    - mvn test -Dtest=CucumberTest
  artifacts:
    access: developer
    expire_in: "1 hour"
    paths:
      - java_sb/target/cucumber-reports/Cucumber.html
    reports:
      junit: java_sb/target/cucumber-reports/Cucumber.xml
  rules:
    - if: *tag_required
    - if: *main_required
  cache: *cache