# créer ou modifier des variables d'environnement
# "variables:" en dehors des jobs => variables globales injectées dans tous les jobs
# "variables:" dans un job => variable locale injectée dans le job
variables:
  MAVEN_VERSION: 3.9.11-eclipse-temurin-21

test:
  image: maven:${MAVEN_VERSION}
  tags:
    - formation
  # commandes de préparation
  before_script:
    - cd java_sb
  # commandes effective du job
  script:
    - mvn test