variables:
  MAVEN_VERSION: 3.9.11-eclipse-temurin-21
  MAVEN_OPTS: -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  MAVEN_ARGS: >
              -s settings.xml
              -Pdefault
              -Dorg.slf4j.simpleLogger.defaultLogLevel=error
  GET_OFFLINE: "-o"
  TRIGGER_CACHE: "off"

image: maven:${MAVEN_VERSION}

stages:
  - building
  - testing
  - qualifying
  - staging


.build:
  stage: building
  tags:
    - formation
  before_script:
    - cd java_sb
  script:
    - mvn verify sonar:sonar || exit 0
    # - mvn package -Dmaven.test.skip=true
  cache:
    key: deps
    policy: push
    paths:
      - .m2/repository
  rules:
    - changes:
        - java_sb/pom.xml
    - if: $TRIGGER_CACHE == "on"

.test:
  stage: testing
  tags:
    - formation
  before_script:
    - cd java_sb
  script:
    - mvn test $GET_OFFLINE
    - cat target/site/jacoco/index.html
  coverage: /Total</td><td class="bar">[0-9]{1,3} of [0-9]{1,3}</td><td class="ctr2">([0-9]{1,3})/
  artifacts:
    access: developer
    expire_in: "1 hour"
    paths:
      - java_sb/target/site/jacoco/jacoco.xml
    reports:
      junit: java_sb/target/surefire-reports/TEST-*.xml
      coverage_report:
        coverage_format: jacoco
        path: java_sb/target/site/jacoco/jacoco.xml
  cache:
    key: deps
    policy: pull
    untracked: true


.sonar:
  stage: qualifying
  tags:
    - formation
  before_script:
    - cd java_sb
  script: 
    - >
      mvn sonar:sonar $GET_OFFLINE
      -Dsonar.projectKey=java_sb
      -Dsonar.java.binaries=target
      -Dsonar.host.url=http://gitlab.lan.fr:9000
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.coverage.jacoco.xmlReportPaths=java_sb/target/site/jacoco/jacoco.xml
      -Dsonar.qualitygate.wait=true

  cache:
    key: deps
    policy: pull
    untracked: true

######## deploy #############################

staging:
  stage: staging
  tags:
    - formation
  before_script:
    - cd java_sb
  script:
    # création de l'app .war
    - mvn package -Dmaven.test.skip=true
    - echo "Deploy !"
  # config pour gérer le déploiement dans Operate > Environments
  environment:
    name: staging
    url: https://dawan.fr
  rules:
    - if: $CI_COMMIT_TAG =~ /v\d+\.\d+$/
    # pour la démo
    - if: $CI_COMMIT_BRANCH == "main"
    
  